### ISSUE TITLE
Permissive license

### ISSUE THREAD

**Issue by pchaigno** [ptomato/sublime_autotools#4]
Hello there, we'd love to use this library to syntax-highlight files on GitHub (through [Linguist](https://github.com/github/linguist)) but in order to do so we need this library to have a more permissive license.

If you didn't have any particular reason for choosing GPL, would you be willing to consider switching to a more permissive license such as MIT, BSD or Apache 2?

Many thanks

**Comment by ptomato** [comment]
That's really exciting, and thank you!

I did choose GPL because the Autoconf highlighter was originally inspired by [this code](https://git.gnome.org/browse/gtksourceview/tree/data/language-specs/m4.lang) which is LGPLv2.1. To my knowledge inspiration does not make it a derivative work in the GPL sense though, so I think there is nothing against my relicensing it. Let me know if you agree.

To relicense it, I believe I'd have to get permission from the other contributors as well, but there have been only two, and I work with one of them, so it shouldn't be too difficult to track them down.

In any case I am willing to license you the Automake and Makefile highlighters under the MIT license. So far I've been the only contributor to those files, and they are definitely not derivative works of any (L)GPL code.

**Comment by pchaigno** [comment]
Thanks for the quick answer :zap: 

> I did choose GPL because the Autoconf highlighter was originally inspired by this code which is LGPLv2.1. To my knowledge inspiration does not make it a derivative work in the GPL sense though, so I think there is nothing against my relicensing it. Let me know if you agree.

@arfon Would you be able to confirm this?

> In any case I am willing to license you the Automake and Makefile highlighters under the MIT license. So far I've been the only contributor to those files, and they are definitely not derivative works of any (L)GPL code.

Unfortunately, I'm mostly interested in the Autoconf grammar, [to highlight M4 files](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fptomato%2Fsublime_autotools%2Fblob%2Fmaster%2FAutoconf.tmLanguage&grammar_text=&code_source=from-text&code_url=&code=AT_BANNER([Library+--+basic])%0D%0A%0D%0AAT_SETUP([successful+linking])%0D%0AAT_KEYWORDS([libopenvswitch])%0D%0AAT_CAPTURE_FILE([log])%0D%0AAT_CHECK(%0D%0A++[test-lib]%2C+[0]%2C%0D%0A++[]%2C+[ignore])%0D%0AAT_CLEANUP%0D%0A) :/

**Comment by arfon** [comment]
> @arfon Would you be able to confirm this?

It depends what 'inspiration means'. Did you copy or translate?

**Comment by ptomato** [comment]
@arfon GtkSourceView's highlighter syntax is quite different from TextMate/Sublime Text's so it would have been difficult to copy directly. But still it's a mostly straightforward translation from one to the other. I contributed about half of the original LGPL file about six years ago (the clever state-machine part wasn't my idea, though, and that was the important inspiration) and then translated it to Sublime Text about three years ago.

Taking a closer look, I see the names of some of the contexts are the same between the two files, as well as some of the regexes.

**Comment by arfon** [comment]
@ptomato it sounds like the most permissive terms reasonable to switch this to, without getting agreement from your co-contributors to the original LGPL file, would be LGPL. Linguist currently doesn't accept LGPL grammars though I'm afraid. You may wish to switch to LGPL now so that it is more reusable in general, even though Linguist can't use it at this time 😞

**Comment by ptomato** [comment]
@arfon I understand, thanks for clarifying. Too bad, I wish I could be of more help.

To my knowledge LGPL or GPL doesn't make any difference on this code, since the exception for dynamic linking doesn't make sense when applied to JSON and XML files. So I will probably keep it GPL to avoid ambiguity.
